/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import fish from "../assets/fish2.glb";

export function Fish(props) {
  const { nodes, animations } = useGLTF(fish);
  const { ref, actions, names } = useAnimations(animations);

  useEffect(() => {
    actions[names[0]].play()
    return () => actions[names[0]]
  }, [actions, names])

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="particle049"
          castShadow
          receiveShadow
          geometry={nodes.particle049.geometry}
          material={nodes.particle049.material}
          position={[-0.909, 1.388, 1.45]}
          rotation={[0, 0.742, -0.075]}
          scale={0.061}
        />
        <mesh
          name="particle048"
          castShadow
          receiveShadow
          geometry={nodes.particle048.geometry}
          material={nodes.particle048.material}
          position={[0.879, 0.666, 0.772]}
          rotation={[0.388, 1.486, -0.317]}
          scale={0.05}
        />
        <mesh
          name="particle047"
          castShadow
          receiveShadow
          geometry={nodes.particle047.geometry}
          material={nodes.particle047.material}
          position={[0.138, 0.081, 0.327]}
          rotation={[-0.085, 1.16, 0.082]}
          scale={0.049}
        />
        <mesh
          name="particle046"
          castShadow
          receiveShadow
          geometry={nodes.particle046.geometry}
          material={nodes.particle046.material}
          position={[0.545, -0.08, 0.929]}
          rotation={[-0.055, 0.512, 0.023]}
          scale={0.076}
        />
        <mesh
          name="particle045"
          castShadow
          receiveShadow
          geometry={nodes.particle045.geometry}
          material={nodes.particle045.material}
          position={[0.893, 1.147, 1.454]}
          rotation={[0.063, 1.451, -0.16]}
          scale={0.058}
        />
        <mesh
          name="particle044"
          castShadow
          receiveShadow
          geometry={nodes.particle044.geometry}
          material={nodes.particle044.material}
          position={[-0.331, 1.678, 1.002]}
          rotation={[-0.006, 0.972, -0.057]}
          scale={0.079}
        />
        <mesh
          name="particle043"
          castShadow
          receiveShadow
          geometry={nodes.particle043.geometry}
          material={nodes.particle043.material}
          position={[0.499, 1.601, 1.04]}
          rotation={[-2.822, 1.102, 2.724]}
          scale={0.072}
        />
        <mesh
          name="particle042"
          castShadow
          receiveShadow
          geometry={nodes.particle042.geometry}
          material={nodes.particle042.material}
          position={[-0.397, 0.835, 0.546]}
          rotation={[-0.011, 0.722, 0.067]}
          scale={0.054}
        />
        <mesh
          name="particle041"
          castShadow
          receiveShadow
          geometry={nodes.particle041.geometry}
          material={nodes.particle041.material}
          position={[0.968, 1.67, -0.404]}
          rotation={[-1.982, 1.409, 1.956]}
          scale={0.066}
        />
        <mesh
          name="particle040"
          castShadow
          receiveShadow
          geometry={nodes.particle040.geometry}
          material={nodes.particle040.material}
          position={[1.248, 1.02, 0.469]}
          rotation={[0.01, 1.302, 0.04]}
          scale={0.07}
        />
        <mesh
          name="particle039"
          castShadow
          receiveShadow
          geometry={nodes.particle039.geometry}
          material={nodes.particle039.material}
          position={[-0.268, 0.336, 0.24]}
          rotation={[0.576, 1.407, -0.442]}
          scale={0.06}
        />
        <mesh
          name="particle038"
          castShadow
          receiveShadow
          geometry={nodes.particle038.geometry}
          material={nodes.particle038.material}
          position={[0.496, 0.037, 0.071]}
          rotation={[0.245, 0.919, -0.218]}
          scale={0.059}
        />
        <mesh
          name="particle037"
          castShadow
          receiveShadow
          geometry={nodes.particle037.geometry}
          material={nodes.particle037.material}
          position={[0.084, 0.263, -0.538]}
          rotation={[-0.093, 1.153, 0.038]}
          scale={0.056}
        />
        <mesh
          name="particle036"
          castShadow
          receiveShadow
          geometry={nodes.particle036.geometry}
          material={nodes.particle036.material}
          position={[-0.081, 1.11, -0.429]}
          rotation={[-0.105, 1.213, 0.111]}
          scale={0.06}
        />
        <mesh
          name="particle035"
          castShadow
          receiveShadow
          geometry={nodes.particle035.geometry}
          material={nodes.particle035.material}
          position={[1.156, 0.339, 0.48]}
          rotation={[0.237, 1.232, -0.224]}
          scale={0.071}
        />
        <mesh
          name="particle034"
          castShadow
          receiveShadow
          geometry={nodes.particle034.geometry}
          material={nodes.particle034.material}
          position={[1.506, 0.66, 0.005]}
          rotation={[-0.242, 1.406, 0.293]}
          scale={0.056}
        />
        <mesh
          name="particle033"
          castShadow
          receiveShadow
          geometry={nodes.particle033.geometry}
          material={nodes.particle033.material}
          position={[0.126, 0.525, 0.088]}
          rotation={[-0.053, 1.113, 0.07]}
          scale={0.056}
        />
        <mesh
          name="particle032"
          castShadow
          receiveShadow
          geometry={nodes.particle032.geometry}
          material={nodes.particle032.material}
          position={[0.378, 0.573, -0.507]}
          rotation={[0.101, 0.558, -0.14]}
          scale={0.05}
        />
        <mesh
          name="particle031"
          castShadow
          receiveShadow
          geometry={nodes.particle031.geometry}
          material={nodes.particle031.material}
          position={[0.749, 1.463, 0.5]}
          rotation={[0.329, 0.74, -0.231]}
          scale={0.077}
        />
        <mesh
          name="particle030"
          castShadow
          receiveShadow
          geometry={nodes.particle030.geometry}
          material={nodes.particle030.material}
          position={[0.202, 0.323, 0.641]}
          rotation={[0.336, 0.451, 0.094]}
          scale={0.063}
        />
        <mesh
          name="particle029"
          castShadow
          receiveShadow
          geometry={nodes.particle029.geometry}
          material={nodes.particle029.material}
          position={[0.509, 0.973, 0.699]}
          rotation={[-2.699, 1.121, 2.814]}
          scale={0.065}
        />
        <mesh
          name="particle028"
          castShadow
          receiveShadow
          geometry={nodes.particle028.geometry}
          material={nodes.particle028.material}
          position={[0.508, 1.06, -0.87]}
          rotation={[-0.008, 1.466, 0.03]}
          scale={0.051}
        />
        <mesh
          name="particle027"
          castShadow
          receiveShadow
          geometry={nodes.particle027.geometry}
          material={nodes.particle027.material}
          position={[0.878, 0.739, -1.211]}
          rotation={[-2.764, 1.132, 2.928]}
          scale={0.047}
        />
        <mesh
          name="particle026"
          castShadow
          receiveShadow
          geometry={nodes.particle026.geometry}
          material={nodes.particle026.material}
          position={[0.428, 1.368, -0.405]}
          rotation={[-0.08, 1.303, 0.162]}
          scale={0.058}
        />
        <mesh
          name="particle025"
          castShadow
          receiveShadow
          geometry={nodes.particle025.geometry}
          material={nodes.particle025.material}
          position={[1.502, 0.457, -0.752]}
          rotation={[-2.834, 1.324, 2.844]}
          scale={0.055}
        />
        <mesh
          name="particle024"
          castShadow
          receiveShadow
          geometry={nodes.particle024.geometry}
          material={nodes.particle024.material}
          position={[0.782, 0.781, 0.09]}
          rotation={[-0.401, 1.494, 0.387]}
          scale={0.058}
        />
        <mesh
          name="particle023"
          castShadow
          receiveShadow
          geometry={nodes.particle023.geometry}
          material={nodes.particle023.material}
          position={[0.875, 0.089, 0.347]}
          rotation={[0.207, 0.748, -0.08]}
          scale={0.078}
        />
        <mesh
          name="particle022"
          castShadow
          receiveShadow
          geometry={nodes.particle022.geometry}
          material={nodes.particle022.material}
          position={[0.969, 0.273, -1.375]}
          rotation={[-2.814, 0.299, 3.03]}
          scale={0.059}
        />
        <mesh
          name="particle021"
          castShadow
          receiveShadow
          geometry={nodes.particle021.geometry}
          material={nodes.particle021.material}
          position={[0.531, 0.465, 0.32]}
          rotation={[0.233, 0.901, -0.144]}
          scale={0.067}
        />
        <mesh
          name="particle020"
          castShadow
          receiveShadow
          geometry={nodes.particle020.geometry}
          material={nodes.particle020.material}
          position={[1.724, 0.783, -0.489]}
          rotation={[-2.731, 1.194, 2.895]}
          scale={0.063}
        />
        <mesh
          name="particle019"
          castShadow
          receiveShadow
          geometry={nodes.particle019.geometry}
          material={nodes.particle019.material}
          position={[1.074, -0.055, -0.998]}
          rotation={[0.443, 1.03, -0.366]}
          scale={0.059}
        />
        <mesh
          name="particle018"
          castShadow
          receiveShadow
          geometry={nodes.particle018.geometry}
          material={nodes.particle018.material}
          position={[0.659, 0.918, -0.444]}
          rotation={[0.155, 0.811, -0.034]}
          scale={0.053}
        />
        <mesh
          name="particle017"
          castShadow
          receiveShadow
          geometry={nodes.particle017.geometry}
          material={nodes.particle017.material}
          position={[0.59, 0.586, -0.767]}
          rotation={[0.197, 1.022, -0.16]}
          scale={0.073}
        />
        <mesh
          name="particle016"
          castShadow
          receiveShadow
          geometry={nodes.particle016.geometry}
          material={nodes.particle016.material}
          position={[1.372, 1.316, -0.413]}
          rotation={[-1.568, 1.358, 1.616]}
          scale={0.067}
        />
        <mesh
          name="particle015"
          castShadow
          receiveShadow
          geometry={nodes.particle015.geometry}
          material={nodes.particle015.material}
          position={[1.062, 0.916, -0.249]}
          rotation={[0.245, 1.04, -0.171]}
          scale={0.046}
        />
        <mesh
          name="particle014"
          castShadow
          receiveShadow
          geometry={nodes.particle014.geometry}
          material={nodes.particle014.material}
          position={[0.217, 0.92, -0.117]}
          rotation={[0.563, 1.465, -0.486]}
          scale={0.069}
        />
        <mesh
          name="particle013"
          castShadow
          receiveShadow
          geometry={nodes.particle013.geometry}
          material={nodes.particle013.material}
          position={[1.375, 0.377, -1.463]}
          rotation={[2.784, 1.417, -2.695]}
          scale={0.068}
        />
        <mesh
          name="particle012"
          castShadow
          receiveShadow
          geometry={nodes.particle012.geometry}
          material={nodes.particle012.material}
          position={[1.081, 0.089, -0.565]}
          rotation={[-2.752, 0.997, 2.79]}
          scale={0.065}
        />
        <mesh
          name="particle011"
          castShadow
          receiveShadow
          geometry={nodes.particle011.geometry}
          material={nodes.particle011.material}
          position={[1.231, 0.507, -0.446]}
          rotation={[0.186, 1.398, -0.139]}
          scale={0.05}
        />
        <mesh
          name="particle010"
          castShadow
          receiveShadow
          geometry={nodes.particle010.geometry}
          material={nodes.particle010.material}
          position={[0.436, 0.373, -0.181]}
          rotation={[0.398, 0.267, -0.17]}
          scale={0.076}
        />
        <mesh
          name="particle009"
          castShadow
          receiveShadow
          geometry={nodes.particle009.geometry}
          material={nodes.particle009.material}
          position={[0.957, 1.172, -0.736]}
          rotation={[-2.256, 1.44, 2.364]}
          scale={0.07}
        />
        <mesh
          name="particle008"
          castShadow
          receiveShadow
          geometry={nodes.particle008.geometry}
          material={nodes.particle008.material}
          position={[0.799, 0.278, -0.88]}
          rotation={[0.288, 1.306, -0.294]}
          scale={0.058}
        />
        <mesh
          name="particle007"
          castShadow
          receiveShadow
          geometry={nodes.particle007.geometry}
          material={nodes.particle007.material}
          position={[1.06, 0.351, -0.014]}
          rotation={[0.242, 0.778, -0.136]}
          scale={0.057}
        />
        <mesh
          name="particle006"
          castShadow
          receiveShadow
          geometry={nodes.particle006.geometry}
          material={nodes.particle006.material}
          position={[1.333, 0.898, -0.701]}
          rotation={[0.207, 1.324, -0.156]}
          scale={0.057}
        />
        <mesh
          name="particle005"
          castShadow
          receiveShadow
          geometry={nodes.particle005.geometry}
          material={nodes.particle005.material}
          position={[0.774, 1.308, 0.01]}
          rotation={[-2.098, 1.452, 2.105]}
          scale={0.076}
        />
        <mesh
          name="particle004"
          castShadow
          receiveShadow
          geometry={nodes.particle004.geometry}
          material={nodes.particle004.material}
          position={[1.457, 0.816, -1.145]}
          rotation={[-2.618, 1.48, 2.625]}
          scale={0.072}
        />
        <mesh
          name="particle003"
          castShadow
          receiveShadow
          geometry={nodes.particle003.geometry}
          material={nodes.particle003.material}
          position={[0.804, 0.476, -0.393]}
          rotation={[-2.674, 1.345, 2.725]}
          scale={0.055}
        />
        <mesh
          name="particle002"
          castShadow
          receiveShadow
          geometry={nodes.particle002.geometry}
          material={nodes.particle002.material}
          position={[0.956, 0.713, -0.74]}
          rotation={[0.349, 1.191, -0.234]}
          scale={0.075}
        />
        <mesh
          name="particle001"
          castShadow
          receiveShadow
          geometry={nodes.particle001.geometry}
          material={nodes.particle001.material}
          position={[1.134, 0.442, -1.021]}
          rotation={[3.139, 1.403, -3.031]}
          scale={0.049}
        />
        <mesh
          name="particle000"
          castShadow
          receiveShadow
          geometry={nodes.particle000.geometry}
          material={nodes.particle000.material}
          position={[1.127, 1.212, -1.233]}
          rotation={[-2.741, 1.361, 2.768]}
          scale={0.068}
        />
      </group>
    </group>
  );
}

export default Fish;