/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sharkingaround (https://sketchfab.com/sharkingaround)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scalloped-hammerhead-juvenile-low-poly-f5adc17c922b48feae76aaea98552dd4
Title: Scalloped Hammerhead Juvenile (LOW POLY)
*/

import React, { useEffect } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import shark from "../assets/shark.glb";

const Shark = () => {
    const { scene, animations } = useGLTF(shark);
    const { ref, actions, names } = useAnimations(animations);
    
    useEffect(() => {
        actions[names[0]].play()
        return () => actions[names[0]]
    }, [actions, names])

    function animate() {
        //NEED TO PREVENT SPEED-UP (keeps increasing to max framrate possible)
        scene.rotation.y -= 0.001;
        requestAnimationFrame(animate);
    }
    requestAnimationFrame(animate);

    return(
        <group ref={ref} dispose={null}>
            <mesh position={[-25, -10, 5]}
                  scale={[5.3, 5.3, 5.3]}
                  rotation={[-5, -4.75, 5]}      
            >
                <primitive object={scene} />
            </mesh>
        </group>
    )
}

export default Shark;