/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PlazaS (https://sketchfab.com/smplaza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sea-turtle-20-2046dd5b34214b52ac5169bd061eab86
Title: Sea Turtle 2.0
*/

import React, { useEffect } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import turtle from "../assets/animated_turtle.glb";

const Turtle = () => {
    const { scene, animations } = useGLTF(turtle);
    const { ref, actions, names } = useAnimations(animations);
    console.log(actions);
    useEffect(() => {
        actions[names[0]].play()
        return () => actions[names[0]]
    }, [actions, names])

    function animate() {
        //NEED TO PREVENT SPEED-UP (keeps increasing to max framrate possible)
        scene.rotation.y -= 0.001;
        requestAnimationFrame(animate);
    }
    requestAnimationFrame(animate);

    return(
        <group ref={ref} dispose={null}>
            <mesh position={[20, -10, -10]}
                  scale={[0.4, 0.4, 0.4]}
                  rotation={[-5, -4.75, 5]}      
            >
                <primitive object={scene} />
            </mesh>
        </group>
    )
}

export default Turtle;